[phases.setup]
nixPkgs = ['python310', 'pip']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'daphne -b 0.0.0.0 -p $PORT hamsa_ws.asgi:application'
