[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip']

[phases.build]
cmds = ['python manage.py collectstatic --noinput --clear']

[start]
cmd = 'daphne -b 0.0.0.0 -p $PORT hamsa_ws.asgi:application'
